# Generated by Django 6.0 on 2025-12-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(unique=True)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP'), ('azure', 'Azure')], max_length=50)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
