# Generated by Django 6.0 on 2026-02-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_is_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_hash',
            field=models.CharField(help_text='SHA256 hash of cleaned content', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether document is already ingested into vector DB'),
        ),
        migrations.AlterField(
            model_name='document',
            name='provider',
            field=models.CharField(help_text='aws | gcp | azure | general', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_url',
            field=models.URLField(help_text='Original URL of the document', unique=True),
        ),
    ]
